### ISSUE TITLE
low framerate

### ISSUE THREAD

**Issue by dimitre** [kylemcdonald/ofxDmx#6]
I'm using the addon together with Enttec Dmx USB Pro and having low framerate (about two updates per second only) using only 6 channels. 
The same setup runs nice with other applications.

here is the relevant part of the test code. Thanks
```c++
//--------------------------------------------------------------
void ofApp::setup(){
	//	dmx.connect("tty.usbserial-EN077864", 6*3);
	dmx.connect("cu.usbserial-EN077864", 6*3);

}

//--------------------------------------------------------------
void ofApp::update(){
	for (int a=0; a<6; a++) {
		int gray = ofNoise(ofGetFrameNum()/10.0f)*255.0;
		float qual = a/(float)6.0;
		float r = gray;
		float g = gray;
		float b = gray;
		dmx.setLevel(a*3 + 1, b);
		dmx.setLevel(a*3 + 2, g);
		dmx.setLevel(a*3 + 3, r);
	}
	//	if(dmx.isConnected()) {
	dmx.update();

	//	}
}
```

**Comment by kylemcdonald** [comment]
if you solved the problem and you have a moment to explain why, other people with similar problems will appreciate it :)

**Comment by dimitre** [comment]
Sure thing. fact is it is still a mystery for me. It was super slow one day, and testing side by side with Madmapper showed it was not cable or enttec issue. 
The other day I compiled again with the same code basically and it worked like a charm.
Thank you for the addon.
